#!/bin/sh

set -e
me=`readlink -e $0`
my_dir=`dirname $me`

for rt in `find $my_dir -name run-tests`
do
    the_dir=`dirname $rt`
    echo Testing $the_dir
    cd $the_dir
    ./run-tests || (echo "Failures in $the_dir, aborting" ; exit 1)
    cd $my_dir
done
echo Yay, all tests pass
