#!/bin/sh

set -e

cd `dirname $0`

for rt in `find . -name run-tests`
do
    the_dir=`dirname $rt`
    echo Testing $the_dir
    pushd $the_dir
    ./run-tests || (echo "Failures in $the_dir, aborting" ; exit 1)
    popd
done
echo Yay, all tests pass
